theme: jekyll-theme-cayman

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "small"

teachermoments:
  demo_url: https://threeflows.herokuapp.com/teachermoments/demo

baseurl: /unconscious-bias